# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 10 May 2018 08:51:24 +0000
*	@ALL	0
*	@user	8
start	@ALL	0
start	@user	1
