<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 10 May 2018 05:39:43 -0400
 */

$conf['title'] = 'TK-Jahreskreis';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['useslash'] = 1;

// end auto-generated content
